# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: Source/Documentation/Manual/requirements.txt

sphinx:
  configuration: Source/Documentation/Manual/conf.py

formats:
  - htmlzip
  - pdf
  - epub
