namespace ORTS.Common.Input
{
    /// <summary>
    /// Specifies game commands.
    /// </summary>
    /// <remarks>
    /// <para>The ordering and naming of these commands is important. They are listed in the UI in the order they are defined in the code, and the first word of each command is the "group" to which it belongs.</para>
    /// </remarks>
    public enum UserCommand
    {
        [GetString("Game Pause Menu")] [GetParticularString("SwitchPanel", "Pause Menu")] GamePauseMenu,
        [GetString("Game Save")] [GetParticularString("SwitchPanel", "Save")] GameSave,
        [GetString("Game Quit")] [GetParticularString("SwitchPanel", "Quit")] GameQuit,
        [GetString("Game Pause")] [GetParticularString("SwitchPanel", "Pause")] GamePause,
        [GetString("Game Screenshot")] [GetParticularString("SwitchPanel", "Screenshot")] GameScreenshot,
        [GetString("Game Fullscreen")] [GetParticularString("SwitchPanel", "Fullscreen")] GameFullscreen,
        [GetString("Game Switch Ahead")] [GetParticularString("SwitchPanel", "Switch Ahead")] GameSwitchAhead,
        [GetString("Game Switch Behind")] [GetParticularString("SwitchPanel", "Switch Behind")] GameSwitchBehind,
        [GetString("Game Switch Picked")] [GetParticularString("SwitchPanel", "Switch Picked")] GameSwitchPicked,
        [GetString("Game Signal Picked")] [GetParticularString("SwitchPanel", "Signal Picked")] GameSignalPicked,
        [GetString("Game Switch With Mouse")] [GetParticularString("SwitchPanel", "Switch With Mouse")] GameSwitchWithMouse,
        [GetString("Game Uncouple With Mouse")] [GetParticularString("SwitchPanel", "Uncouple With Mouse")] GameUncoupleWithMouse,
        [GetString("Game Change Cab")] [GetParticularString("SwitchPanel", "Change Cab")] GameChangeCab,
        [GetString("Game Request Control")] [GetParticularString("SwitchPanel", "Request Control")] GameRequestControl,
        [GetString("Game Multi Player Dispatcher")] [GetParticularString("SwitchPanel", "Multi Player Dispatcher")] GameMultiPlayerDispatcher,
        [GetString("Game Multi Player Texting")] [GetParticularString("SwitchPanel", "Multi Player Texting")] GameMultiPlayerTexting,
        [GetString("Game Switch Manual Mode")] [GetParticularString("SwitchPanel", "Switch Manual")] GameSwitchManualMode,
        [GetString("Game Reset Out Of Control Mode")] [GetParticularString("SwitchPanel", "Reset Out Of Control")] GameResetOutOfControlMode,
        [GetString("Game Clear Signal Forward")] [GetParticularString("SwitchPanel", "Clear Signal Forward")] GameClearSignalForward,
        [GetString("Game Clear Signal Backward")] [GetParticularString("SwitchPanel", "Clear Signal Backward")] GameClearSignalBackward,
        [GetString("Game Reset Signal Forward")] [GetParticularString("SwitchPanel", "Reset Signal Forward")] GameResetSignalForward,
        [GetString("Game Reset Signal Backward")] [GetParticularString("SwitchPanel", "Reset Signal Backward")] GameResetSignalBackward,
        [GetString("Game Autopilot Mode")] [GetParticularString("SwitchPanel", "Autopilot")] GameAutopilotMode,
        [GetString("Game Suspend Old Player")] [GetParticularString("SwitchPanel", "Suspend Old Player")] GameSuspendOldPlayer,

        [GetString("Display Next Window Tab")] [GetParticularString("SwitchPanel", "Next Window Tab")] DisplayNextWindowTab,
        [GetString("Display Help Window")] [GetParticularString("SwitchPanel", "Help")] DisplayHelpWindow,
        [GetString("Display Track Monitor Window")] [GetParticularString("SwitchPanel", "Track Monitor")] DisplayTrackMonitorWindow,
        [GetString("Display HUD")] [GetParticularString("SwitchPanel", "HUD")] DisplayHUD,
        [GetString("Display Train Driving Window")] [GetParticularString("SwitchPanel", "Train Driving")] DisplayTrainDrivingWindow,
        [GetString("Display Multi Player Window")] [GetParticularString("SwitchPanel", "Multi Player")] DisplayMultiPlayerWindow,
        [GetString("Display Car Labels")] [GetParticularString("SwitchPanel", "Car Labels")] DisplayCarLabels,
        [GetString("Display Station Labels")] [GetParticularString("SwitchPanel", "Station Labels")] DisplayStationLabels,
        [GetString("Display Switch Window")] [GetParticularString("SwitchPanel", "Switch")] DisplaySwitchWindow,
        [GetString("Display Train Operations Window")] [GetParticularString("SwitchPanel", "Train Operations")] DisplayTrainOperationsWindow,
        [GetString("Display Train Dpu Window")] [GetParticularString("SwitchPanel", "Train Dpu")] DisplayTrainDpuWindow,
        [GetString("Display Next Station Window")] [GetParticularString("SwitchPanel", "Next Station")] DisplayNextStationWindow,
        [GetString("Display Compass Window")] [GetParticularString("SwitchPanel", "Compass")] DisplayCompassWindow,
        [GetString("Display Train List Window")] [GetParticularString("SwitchPanel", "Train List")] DisplayTrainListWindow,
        [GetString("Display EOT List Window")] [GetParticularString("SwitchPanel", "EOT List")] DisplayEOTListWindow,

        [GetString("Debug Speed Up")] [GetParticularString("SwitchPanel", "Speed")] DebugSpeedUp,
        [GetString("Debug Speed Down")] [GetParticularString("SwitchPanel", "Speed")] DebugSpeedDown,
        [GetString("Debug Speed Reset")] [GetParticularString("SwitchPanel", "Speed Reset")] DebugSpeedReset,
        [GetString("Debug Overcast Increase")] [GetParticularString("SwitchPanel", "Overcast")] DebugOvercastIncrease,
        [GetString("Debug Overcast Decrease")] [GetParticularString("SwitchPanel", "Overcast")] DebugOvercastDecrease,
        [GetString("Debug Fog Increase")] [GetParticularString("SwitchPanel", "Fog")] DebugFogIncrease,
        [GetString("Debug Fog Decrease")] [GetParticularString("SwitchPanel", "Fog")] DebugFogDecrease,
        [GetString("Debug Precipitation Increase")] [GetParticularString("SwitchPanel", "Precipitation")] DebugPrecipitationIncrease,
        [GetString("Debug Precipitation Decrease")] [GetParticularString("SwitchPanel", "Precipitation")] DebugPrecipitationDecrease,
        [GetString("Debug Precipitation Liquidity Increase")] [GetParticularString("SwitchPanel", "Precipitation Liquidity")] DebugPrecipitationLiquidityIncrease,
        [GetString("Debug Precipitation Liquidity Decrease")] [GetParticularString("SwitchPanel", "Precipitation Liquidity")] DebugPrecipitationLiquidityDecrease,
        [GetString("Debug Weather Change")] [GetParticularString("SwitchPanel", "Weather Change")] DebugWeatherChange,
        [GetString("Debug Clock Forwards")] [GetParticularString("SwitchPanel", "Clock Forwards")] DebugClockForwards,
        [GetString("Debug Clock Backwards")] [GetParticularString("SwitchPanel", "Clock Backwards")] DebugClockBackwards,
        [GetString("Debug Logger")] [GetParticularString("SwitchPanel", "Logger")] DebugLogger,
        [GetString("Debug Lock Shadows")] [GetParticularString("SwitchPanel", "Lock Shadows")] DebugLockShadows,
        [GetString("Debug Dump Keyboard Map")] [GetParticularString("SwitchPanel", "Dump Keyboard Map")] DebugDumpKeymap,
        [GetString("Debug Log Render Frame")] [GetParticularString("SwitchPanel", "Log Render Frame")] DebugLogRenderFrame,
        [GetString("Debug Tracks")] [GetParticularString("SwitchPanel", "Tracks")] DebugTracks,
        [GetString("Debug Signalling")] [GetParticularString("SwitchPanel", "Signalling")] DebugSignalling,
        [GetString("Debug Reset Wheel Slip")] [GetParticularString("SwitchPanel", "Reset Wheel Slip")] DebugResetWheelSlip,
        [GetString("Debug Toggle Advanced Adhesion")] [GetParticularString("SwitchPanel", "Toggle Advanced Adhesion")] DebugToggleAdvancedAdhesion,
        [GetString("Debug Sound Form")] [GetParticularString("SwitchPanel", "Sound Form")] DebugSoundForm,
        [GetString("Debug Physics Form")] [GetParticularString("SwitchPanel", "Physics Form")] DebugPhysicsForm,
        [GetString("Debug Toggle Confirmations")] [GetParticularString("SwitchPanel", "Toggle Confirmations")] DebugToggleConfirmations,

        [GetString("Camera Cab")] [GetParticularString("SwitchPanel", "Camera Cab")] CameraCab,
        [GetString("Camera Change Passenger Viewpoint")] [GetParticularString("SwitchPanel", "Camera Change Passenger Viewpoint")] CameraChangePassengerViewPoint,
        [GetString("Camera Toggle 3D Cab")] [GetParticularString("SwitchPanel", "Camera Toggle 3D Cab")] CameraToggleThreeDimensionalCab,
        [GetString("Camera Toggle Show Cab")] [GetParticularString("SwitchPanel", "Camera Toggle Show Cab")] CameraToggleShowCab,
        [GetString("Camera Toggle Letterbox Cab")] [GetParticularString("SwitchPanel", "Camera Toggle Letterbox Cab")] CameraToggleLetterboxCab,
        [GetString("Camera Head Out Forward")] [GetParticularString("SwitchPanel", "Camera Head Out Forward")] CameraHeadOutForward,
        [GetString("Camera Head Out Backward")] [GetParticularString("SwitchPanel", "Camera Head Out Backward")] CameraHeadOutBackward,
        [GetString("Camera Outside Front")] [GetParticularString("SwitchPanel", "Camera Outside Front")] CameraOutsideFront,
        [GetString("Camera Outside Rear")] [GetParticularString("SwitchPanel", "Camera Outside Rear")] CameraOutsideRear,
        [GetString("Camera Trackside")] [GetParticularString("SwitchPanel", "Camera Trackside")] CameraTrackside,
        [GetString("Camera SpecialTracksidePoint")] [GetParticularString("SwitchPanel", "Camera SpecialTracksidePoint")] CameraSpecialTracksidePoint,
        [GetString("Camera Passenger")] [GetParticularString("SwitchPanel", "Camera Passenger")] CameraPassenger,
        [GetString("Camera Brakeman")] [GetParticularString("SwitchPanel", "Camera Brakeman")] CameraBrakeman,
        [GetString("Camera Free")] [GetParticularString("SwitchPanel", "Camera Free")] CameraFree,
        [GetString("Camera Previous Free")] [GetParticularString("SwitchPanel", "Camera Previous Free")] CameraPreviousFree,
        [GetString("Camera Reset")] [GetParticularString("SwitchPanel", "Camera Reset")] CameraReset,
        [GetString("Camera Move Fast")] [GetParticularString("SwitchPanel", "Camera Move Fast")] CameraMoveFast,
        [GetString("Camera Move Slow")] [GetParticularString("SwitchPanel", "Camera Move Slow")] CameraMoveSlow,
        [GetString("Camera Pan (Rotate) Left")] [GetParticularString("SwitchPanel", "Camera Pan (Rotate) Left")] CameraPanLeft,
        [GetString("Camera Pan (Rotate) Right")] [GetParticularString("SwitchPanel", "Camera Pan (Rotate) Right")] CameraPanRight,
        [GetString("Camera Pan (Rotate) Up")] [GetParticularString("SwitchPanel", "Camera Pan (Rotate) Up")] CameraPanUp,
        [GetString("Camera Pan (Rotate) Down")] [GetParticularString("SwitchPanel", "Camera Pan (Rotate) Down")] CameraPanDown,
        [GetString("Camera Zoom In (Move Z)")] [GetParticularString("SwitchPanel", "Camera Zoom In (Move Z)")] CameraZoomIn,
        [GetString("Camera Zoom Out (Move Z)")] [GetParticularString("SwitchPanel", "Camera Zoom Out (Move Z)")] CameraZoomOut,
        [GetString("Camera Rotate (Pan) Left")] [GetParticularString("SwitchPanel", "Camera Rotate (Pan) Left")] CameraRotateLeft,
        [GetString("Camera Rotate (Pan) Right")] [GetParticularString("SwitchPanel", "Camera Rotate (Pan) Right")] CameraRotateRight,
        [GetString("Camera Rotate (Pan) Up")] [GetParticularString("SwitchPanel", "Camera Rotate (Pan) Up")] CameraRotateUp,
        [GetString("Camera Rotate (Pan) Down")] [GetParticularString("SwitchPanel", "Camera Rotate (Pan) Down")] CameraRotateDown,
        [GetString("Camera Car Next")] [GetParticularString("SwitchPanel", "Camera Car Next")] CameraCarNext,
        [GetString("Camera Car Previous")] [GetParticularString("SwitchPanel", "Camera Car Previous")] CameraCarPrevious,
        [GetString("Camera Car First")] [GetParticularString("SwitchPanel", "Camera Car First")] CameraCarFirst,
        [GetString("Camera Car Last")] [GetParticularString("SwitchPanel", "Camera Car Last")] CameraCarLast,
        [GetString("Camera Jumping Trains")] [GetParticularString("SwitchPanel", "Camera Jumping Trains")] CameraJumpingTrains,
        [GetString("Camera Jump Back Player")] [GetParticularString("SwitchPanel", "Camera Jump Back Player")] CameraJumpBackPlayer,
        [GetString("Camera Jump See Switch")] [GetParticularString("SwitchPanel", "Camera Jump See Switch")] CameraJumpSeeSwitch,
        [GetString("Camera Vibrate")] [GetParticularString("SwitchPanel", "Camera Vibrate")] CameraVibrate,
        [GetString("Camera Scroll Right")] [GetParticularString("SwitchPanel", "Camera Scroll Right")] CameraScrollRight,
        [GetString("Camera Scroll Left")] [GetParticularString("SwitchPanel", "Camera Scroll Left")] CameraScrollLeft,
        [GetString("Camera Browse Backwards")] [GetParticularString("SwitchPanel", "Camera Browse Backwards")] CameraBrowseBackwards,
        [GetString("Camera Browse Forwards")] [GetParticularString("SwitchPanel", "Camera Browse Forwards")] CameraBrowseForwards,

        [GetString("Control Forwards")] [GetParticularString("SwitchPanel", "Forwards")] ControlForwards,
        [GetString("Control Backwards")] [GetParticularString("SwitchPanel", "Backwards")] ControlBackwards,
        [GetString("Control Throttle Increase")] [GetParticularString("SwitchPanel", "Throttle")] ControlThrottleIncrease,
        [GetString("Control Throttle Decrease")] [GetParticularString("SwitchPanel", "Throttle")] ControlThrottleDecrease,
        [GetString("Control Throttle Zero")] [GetParticularString("SwitchPanel", "Throttle Zero")] ControlThrottleZero,
        [GetString("Control Gear Up")] [GetParticularString("SwitchPanel", "Gear")] ControlGearUp,
        [GetString("Control Gear Down")] [GetParticularString("SwitchPanel", "Gear")] ControlGearDown,
        [GetString("Control Train Brake Increase")] [GetParticularString("SwitchPanel", "Train Brake")] ControlTrainBrakeIncrease,
        [GetString("Control Train Brake Decrease")] [GetParticularString("SwitchPanel", "Train Brake")] ControlTrainBrakeDecrease,
        [GetString("Control Train Brake Zero")] [GetParticularString("SwitchPanel", "Train Brake Zero")] ControlTrainBrakeZero,
        [GetString("Control Engine Brake Increase")] [GetParticularString("SwitchPanel", "Engine Brake")] ControlEngineBrakeIncrease,
        [GetString("Control Engine Brake Decrease")] [GetParticularString("SwitchPanel", "Engine Brake")] ControlEngineBrakeDecrease,
        [GetString("Control Brakeman Brake Increase")] [GetParticularString("SwitchPanel", "Brakeman Brake")] ControlBrakemanBrakeIncrease,
        [GetString("Control Brakeman Brake Decrease")] [GetParticularString("SwitchPanel", "Brakeman Brake")] ControlBrakemanBrakeDecrease,
        [GetString("Control Dynamic Brake Increase")] [GetParticularString("SwitchPanel", "Dynamic Brake")] ControlDynamicBrakeIncrease,
        [GetString("Control Dynamic Brake Decrease")] [GetParticularString("SwitchPanel", "Dynamic Brake")] ControlDynamicBrakeDecrease,
        [GetString("Control Bail Off")] [GetParticularString("SwitchPanel", "Bail Off")] ControlBailOff,
        [GetString("Control Brake Quick Release")] [GetParticularString("SwitchPanel", "Brake Quick Release")] ControlBrakeQuickRelease,
        [GetString("Control Brake Overcharge")] [GetParticularString("SwitchPanel", "Brake Overcharge")] ControlBrakeOvercharge,
        [GetString("Control Initialize Brakes")] [GetParticularString("SwitchPanel", "Initialize Brakes")] ControlInitializeBrakes,
        [GetString("Control Handbrake Full")] [GetParticularString("SwitchPanel", "Handbrake Full")] ControlHandbrakeFull,
        [GetString("Control Handbrake None")] [GetParticularString("SwitchPanel", "Handbrake None")] ControlHandbrakeNone,
        [GetString("Control Odometer Show/Hide")] [GetParticularString("SwitchPanel", "Odometer Show/Hide")] ControlOdoMeterShowHide,
        [GetString("Control Odometer Reset")] [GetParticularString("SwitchPanel", "Odometer Reset")] ControlOdoMeterReset,
        [GetString("Control Odometer Direction")] [GetParticularString("SwitchPanel", "Odometer Direction")] ControlOdoMeterDirection,
        [GetString("Control Retainers On")] [GetParticularString("SwitchPanel", "Retainers On")] ControlRetainersOn,
        [GetString("Control Retainers Off")] [GetParticularString("SwitchPanel", "Retainers Off")] ControlRetainersOff,
        [GetString("Control Brake Hose Connect")] [GetParticularString("SwitchPanel", "Brake Hose Connect")] ControlBrakeHoseConnect,
        [GetString("Control Brake Hose Disconnect")] [GetParticularString("SwitchPanel", "Brake Hose Disconnect")] ControlBrakeHoseDisconnect,
        [GetString("Control Alerter")] [GetParticularString("SwitchPanel", "Alerter")] ControlAlerter,
        [GetString("Control Emergency Push Button")] [GetParticularString("SwitchPanel", "Emergency")] ControlEmergencyPushButton,
        [GetString("Control EOT Emergency Brake")] [GetParticularString("SwitchPanel", "EOT Emergency Brake")] ControlEOTEmergencyBrake,
        [GetString("Control Sander")] [GetParticularString("SwitchPanel", "Sander")] ControlSander,
        [GetString("Control Sander Toggle")] [GetParticularString("SwitchPanel", "Sander Toggle")] ControlSanderToggle,
        [GetString("Control Wiper")] [GetParticularString("SwitchPanel", "Wiper")] ControlWiper,
        [GetString("Control Horn")] [GetParticularString("SwitchPanel", "Horn")] ControlHorn,
        [GetString("Control Bell")] [GetParticularString("SwitchPanel", "Bell")] ControlBell,
        [GetString("Control Bell Toggle")] [GetParticularString("SwitchPanel", "Bell Toggle")] ControlBellToggle,
        [GetString("Control Door Left")] [GetParticularString("SwitchPanel", "Door Left")] ControlDoorLeft,
        [GetString("Control Door Right")] [GetParticularString("SwitchPanel", "Door Right")] ControlDoorRight,
        [GetString("Control Mirror")] [GetParticularString("SwitchPanel", "Mirror")] ControlMirror,
        [GetString("Control Light")] [GetParticularString("SwitchPanel", "Light")] ControlLight,
        [GetString("Control Pantograph 1")] [GetParticularString("SwitchPanel", "Pantograph 1")] ControlPantograph1,
        [GetString("Control Pantograph 2")] [GetParticularString("SwitchPanel", "Pantograph 2")] ControlPantograph2,
        [GetString("Control Pantograph 3")] [GetParticularString("SwitchPanel", "Pantograph 3")] ControlPantograph3,
        [GetString("Control Pantograph 4")] [GetParticularString("SwitchPanel", "Pantograph 4")] ControlPantograph4,
        [GetString("Control Battery Close")] [GetParticularString("SwitchPanel", "Battery Close")] ControlBatterySwitchClose,
        [GetString("Control Battery Open")] [GetParticularString("SwitchPanel", "Battery Open")] ControlBatterySwitchOpen,
        [GetString("Control Master Key")] [GetParticularString("SwitchPanel", "Master Key")] ControlMasterKey,
        [GetString("Control Service Retention")] [GetParticularString("SwitchPanel", "Service Retention")] ControlServiceRetention,
        [GetString("Control Service Retention Cancellation")] [GetParticularString("SwitchPanel", "Service Retention Cancellation")] ControlServiceRetentionCancellation,
        [GetString("Control Circuit Breaker Closing Order")] [GetParticularString("SwitchPanel", "Circuit Breaker Closing Order")] ControlCircuitBreakerClosingOrder,
        [GetString("Control Circuit Breaker Opening Order")] [GetParticularString("SwitchPanel", "Circuit Breaker Opening Order")] ControlCircuitBreakerOpeningOrder,
        [GetString("Control Circuit Breaker Closing Authorization")] [GetParticularString("SwitchPanel", "Circuit Breaker Closing Authorization")] ControlCircuitBreakerClosingAuthorization,
        [GetString("Control Traction Cut-Off Relay Closing Order")] [GetParticularString("SwitchPanel", "Traction Cut-Off Relay Closing Order")] ControlTractionCutOffRelayClosingOrder,
        [GetString("Control Traction Cut-Off Relay Opening Order")] [GetParticularString("SwitchPanel", "Traction Cut-Off Relay Opening Order")] ControlTractionCutOffRelayOpeningOrder,
        [GetString("Control Traction Cut-Off Relay Closing Authorization")] [GetParticularString("SwitchPanel", "Traction Cut-Off Relay Closing Authorization")] ControlTractionCutOffRelayClosingAuthorization,
        [GetString("Control Electric Train Supply")] [GetParticularString("SwitchPanel", "Electric Train Supply")] ControlElectricTrainSupply,
        [GetString("Control Diesel Player")] [GetParticularString("SwitchPanel", "Diesel Player")] ControlDieselPlayer,
        [GetString("Control Diesel Helper")] [GetParticularString("SwitchPanel", "Diesel Helper")] ControlDieselHelper,
        [GetString("Control Headlight Increase")] [GetParticularString("SwitchPanel", "Headlight")] ControlHeadlightIncrease,
        [GetString("Control Headlight Decrease")] [GetParticularString("SwitchPanel", "Headlight")] ControlHeadlightDecrease,
        [GetString("Control Injector 1 Increase")] [GetParticularString("SwitchPanel", "Injector 1")] ControlInjector1Increase,
        [GetString("Control Injector 1 Decrease")] [GetParticularString("SwitchPanel", "Injector 1")] ControlInjector1Decrease,
        [GetString("Control Injector 1")] [GetParticularString("SwitchPanel", "Injector 1")] ControlInjector1,
        [GetString("Control Injector 2 Increase")] [GetParticularString("SwitchPanel", "Injector 2")] ControlInjector2Increase,
        [GetString("Control Injector 2 Decrease")] [GetParticularString("SwitchPanel", "Injector 2")] ControlInjector2Decrease,
        [GetString("Control Injector 2")] [GetParticularString("SwitchPanel", "Injector 2")] ControlInjector2,
        [GetString("Control Blowdown Valve")] [GetParticularString("SwitchPanel", "Blowdown Valve")] ControlBlowdownValve,
        [GetString("Control Blower Increase")] [GetParticularString("SwitchPanel", "Blower")] ControlBlowerIncrease,
        [GetString("Control Blower Decrease")] [GetParticularString("SwitchPanel", "Blower")] ControlBlowerDecrease,
        [GetString("Control Steam Heat Increase")] [GetParticularString("SwitchPanel", "Steam Heat")] ControlSteamHeatIncrease,
        [GetString("Control Steam Heat Decrease")] [GetParticularString("SwitchPanel", "Steam Heat")] ControlSteamHeatDecrease,
        [GetString("Control Damper Increase")] [GetParticularString("SwitchPanel", "Damper")] ControlDamperIncrease,
        [GetString("Control Damper Decrease")] [GetParticularString("SwitchPanel", "Damper")] ControlDamperDecrease,
        [GetString("Control Firebox Open")] [GetParticularString("SwitchPanel", "Firebox Open")] ControlFireboxOpen,
        [GetString("Control Firebox Close")] [GetParticularString("SwitchPanel", "Firebox Close")] ControlFireboxClose,
        [GetString("Control Firing Rate Increase")] [GetParticularString("SwitchPanel", "Firing Rate")] ControlFiringRateIncrease,
        [GetString("Control Firing Rate Decrease")] [GetParticularString("SwitchPanel", "Firing Rate")] ControlFiringRateDecrease,
        [GetString("Control Fire Shovel Full")] [GetParticularString("SwitchPanel", "Fire Shovel Full")] ControlFireShovelFull,
        [GetString("Control Cylinder Cocks")] [GetParticularString("SwitchPanel", "Cylinder Cocks")] ControlCylinderCocks,
        [GetString("Control Large Ejector Increase")] [GetParticularString("SwitchPanel", "Large Ejector")] ControlLargeEjectorIncrease,
        [GetString("Control Large Ejector Decrease")] [GetParticularString("SwitchPanel", "Large Ejector")] ControlLargeEjectorDecrease,
        [GetString("Control Small Ejector Increase")] [GetParticularString("SwitchPanel", "Small Ejector")] ControlSmallEjectorIncrease,
        [GetString("Control Small Ejector Decrease")] [GetParticularString("SwitchPanel", "Small Ejector")] ControlSmallEjectorDecrease,
        [GetString("Control Vacuum Exhauster")] [GetParticularString("SwitchPanel", "Vacuum Exhauster")] ControlVacuumExhausterPressed,
        [GetString("Control Cylinder Compound")] [GetParticularString("SwitchPanel", "Cylinder Compound")] ControlCylinderCompound,
        [GetString("Control Firing")] [GetParticularString("SwitchPanel", "Firing")] ControlFiring,
        [GetString("Control Refill")] [GetParticularString("SwitchPanel", "Refill")] ControlRefill,
        [GetString("Control Discrete Unload")] [GetParticularString("SwitchPanel", "Discrete Unload")] ControlDiscreteUnload,
        [GetString("Control Water Scoop")] [GetParticularString("SwitchPanel", "Water Scoop")] ControlWaterScoop,
        [GetString("Control ImmediateRefill")] [GetParticularString("SwitchPanel", "ImmediateRefill")] ControlImmediateRefill,
        [GetString("Control Turntable Clockwise")] [GetParticularString("SwitchPanel", "Turntable Clockwise")] ControlTurntableClockwise,
        [GetString("Control Turntable Counterclockwise")] [GetParticularString("SwitchPanel", "Turntable Counterclockwise")] ControlTurntableCounterclockwise,
        [GetString("Control Generic Item 1")] [GetParticularString("SwitchPanel", "Generic Item 1")] ControlGenericItem1,
        [GetString("Control Generic Item 2")] [GetParticularString("SwitchPanel", "Generic Item 2")] ControlGenericItem2,
        [GetString("Control TCS Generic 1")] [GetParticularString("SwitchPanel", "TCS Generic 1")] ControlTCSGeneric1,
        [GetString("Control TCS Generic 2")] [GetParticularString("SwitchPanel", "TCS Generic 2")] ControlTCSGeneric2,
        [GetString("Control Cab Radio")] [GetParticularString("SwitchPanel", "Cab Radio")] ControlCabRadio,
        [GetString("Control AI Fire On")] [GetParticularString("SwitchPanel", "AI Fire On")] ControlAIFireOn,
        [GetString("Control AI Fire Off")] [GetParticularString("SwitchPanel", "AI Fire Off")] ControlAIFireOff,
        [GetString("Control AI Fire Reset")] [GetParticularString("SwitchPanel", "AI Fire Reset")] ControlAIFireReset,

        // Cruise Control
        [GetString("Control Speed Regulator Mode Increase")] [GetParticularString("SwitchPanel", "Speed Regulator Mode")] ControlSpeedRegulatorModeIncrease,
        [GetString("Control Speed Regulator Mode Descrease")] [GetParticularString("SwitchPanel", "Speed Regulator Mode Descrease")] ControlSpeedRegulatorModeDecrease,
        [GetString("Control Selected Speed Increase")] [GetParticularString("SwitchPanel", "Selected Speed")] ControlSpeedRegulatorSelectedSpeedIncrease,
        [GetString("Control Selected Speed Decrease")] [GetParticularString("SwitchPanel", "Selected Speed")] ControlSpeedRegulatorSelectedSpeedDecrease,
        [GetString("Control Speed Regulator Max Acceleration Increase")] [GetParticularString("SwitchPanel", "Speed Regulator Max Acceleration")] ControlSpeedRegulatorMaxAccelerationIncrease,
        [GetString("Control Speed Regulator Max Acceleration Decrease")] [GetParticularString("SwitchPanel", "Speed Regulator Max Acceleration")] ControlSpeedRegulatorMaxAccelerationDecrease,
        [GetString("Control Number Of Axles Increase")] [GetParticularString("SwitchPanel", "Number Of Axles")] ControlNumberOfAxlesIncrease,
        [GetString("Control Number Of Axles Decrease")] [GetParticularString("SwitchPanel", "Number Of Axles")] ControlNumberOfAxlesDecrease,
        [GetString("Control Restricted Speed Zone Active")] [GetParticularString("SwitchPanel", "Restricted Speed Zone Active")] ControlRestrictedSpeedZoneActive,
        [GetString("Control Cruise Control Mode Increase")] [GetParticularString("SwitchPanel", "Cruise Control Mode")] ControlCruiseControlModeIncrease,
        [GetString("Control Cruise Control Mode Decrease")] [GetParticularString("SwitchPanel", "Cruise Control Mode")] ControlCruiseControlModeDecrease,
        [GetString("Control Train Type Change (Passenger/Cargo)")] [GetParticularString("SwitchPanel", "Train Type Change (Passenger/Cargo)")] ControlTrainTypePaxCargo,
        [GetString("Control Selected Speed To Zero")] [GetParticularString("SwitchPanel", "Selected Speed To Zero")] ControlSpeedRegulatorSelectedSpeedToZero,
        //Distributed power
        [GetString("Control DP Move To Front")] [GetParticularString("SwitchPanel", "DP Move To Front")] ControlDPMoveToFront,
        [GetString("Control DP Move To Back")] [GetParticularString("SwitchPanel", "DP Move To Back")] ControlDPMoveToBack,
        [GetString("Control DP Traction")] [GetParticularString("SwitchPanel", "DP Traction")] ControlDPTraction,
        [GetString("Control DP Idle")] [GetParticularString("SwitchPanel", "DP Idle")] ControlDPIdle,
        [GetString("Control DP Brake")] [GetParticularString("SwitchPanel", "DP Brake")] ControlDPBrake,
        [GetString("Control DP More")] [GetParticularString("SwitchPanel", "DP More")] ControlDPMore,
        [GetString("Control DP Less")] [GetParticularString("SwitchPanel", "DP Less")] ControlDPLess,
    }
}
