name: Check Potential Conflicts
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Potential Conflicts Checker
        uses: outsideris/potential-conflicts-checker-action@v0.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}